### ISSUE TITLE
[BUG] cannot open dropship

### ISSUE THREAD

**Issue by CoolLKKPS** [Ssencipe/Overhaul_Moons#3]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ItemDropship.LandShipClientRpc () (at <85e462e10f76479c8e6307fde94ca1d1>:IL_00D7)
ItemDropship.__rpc_handler_1496861823 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <85e462e10f76479c8e6307fde94ca1d1>:IL_002E)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
ItemDropship:LandShipClientRpc()
ItemDropship:LandShipOnServer()
ItemDropship:DMD<ItemDropship::Update>(ItemDropship)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ItemDropship.LandShipClientRpc () (at <85e462e10f76479c8e6307fde94ca1d1>:IL_00D7)
ItemDropship.LandShipOnServer () (at <85e462e10f76479c8e6307fde94ca1d1>:IL_004A)
(wrapper dynamic-method) ItemDropship.DMD<ItemDropship::Update>(ItemDropship)

**Comment by CoolLKKPS** [comment]
@Ssencipe

**Comment by Ssencipe** [comment]
Should be good to go now.

**Comment by CoolLKKPS** [comment]
yes dropship issue fixed, but uh i got some error logs yesterday and im not sure is ok or not, will provide `logoutput` for u

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17675399/LogOutput.log)

**Comment by CoolLKKPS** [comment]
@Ssencipe tested in dev mode, im not sure these error logs can safety ignore or not
